#!/usr/bin/env bash
#write a script to install an nginx web server

sudo apt-get update -y && sudo apt-get upgrade -y

sudo apt-get install -y nginx
sudo service nginx start

sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html