#!/usr/bin/env bash
#install nginx and configure it

##update
sudo apt-get update -y

#install nginx
sudo apt-get install -y nginx

#configure home page for nginx
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html

#configure redirection 
sudo sed -i 'listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart