#!/usr/bin/env bash
#install nginx and configure it

sudo apt-get update -y && sudo apt-get upgrade -y

sudo apt-get install -y nginx
sudo service nginx start

sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled/default
sudo sed -i ;\#root /var/www/html;#a\\tlocation /redirect_me/ {\n\t\return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
