#!/usr/bin/env bash
#install nginx and configure it

sudo apt-get -y update
sudo apt-get  -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i ;\#root /var/www/html;#a\\tlocation /redirect_me/ {\n\t\return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
