#!/usr/bin/env bash
#install nginx and configure it and add a custom 404 page and a redirection page

# Update and upgrade packages
sudo apt-get update -y && sudo apt-get upgrade -y

# Install nginx
sudo apt-get install -y nginx

# Set up default nginx page
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html

# Configure custom 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/^listen 80 default_server/a\
error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart nginx service
sudo service nginx restart