#!/usr/bin/env bash
#install nginx and configure it

sudo apt-get update -y && sudo apt-get upgrade -y

sudo apt-get install -y nginx

# sudo ufw allow 'Nginx HTTP'
# sudo chown -R "$USER":"$USER" /var/www/html
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled/default

# shellcheck disable=SC1004
sudo sed -i '/listen 80 default_server/a\
rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4/ permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/^listen 80 default_server/a\
error_page 404 /custom_404.html/ internal;' /etc/nginx/sites-available/default

sudo service nginx restart