#!/usr/bin/env bash
#a script that installs nginx to a remote server

sudo apt update -y
sudo apt upgrade -y

#install nginx
sudo apt install nginx -y

#start nginx
sudo service nginx start

#modify permissions for web files
sudo chown -R "$USER":"$USER" /var/www/html

#modify root server page
echo "Hello world" > /var/www/html/index.nginx-debian.html

#modify 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

#modify nginx config file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }

    add_header X-Served-By \$hostname;
}" > sudo tee /etc/nginx/sites-available/default

#restart nginx
sudo systemctl restart nginx
