#!/usr/bin/env bash
#install nginx and configure it and add a custom 404 page and a redirection page to server

# Update and upgrade packages
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Set up default nginx page
sudo echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled/default

# shellcheck disable=SC1004
sudo sed -i '/listen 80 default_server/a\
rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4/ permanent;' /etc/nginx/sites-available/default


# Configure custom 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/^listen 80 default_server/a\
error_page 404 /404.html;' /etc/nginx/sites-available/default

#add customed header
sudo echo "add_header X-Served-By $HOSTNAME;" | sudo tee -a /etc/nginx/sites-available/default

#restart nginx
sudo service nginx restart
