#!/usr/bin/env bash
#a script that installs nginx to a remote server

sudo apt update -y
sudo apt upgrade -y

#install nginx
sudo apt install nginx -y

#start nginx
sudo service nginx start

#modify permissions for web files
sudo chown -R "$USER":"$USER" /var/www/html

#modify root server page
echo "Hello world" > /var/www/html/index.nginx-debian.html

#append new location of redirection
sudo sed -i '\#root /var/www/html;#a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

#configure 404 page path
sudo sed -i '\#root /var/www/html;#a\\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

#modify 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

#restart nginx
sudo service nginx restart
