#!/usr/bin/env bash
#script to install a haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy.cfg >/dev/null <<EOL

global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 54.237.61.71:80 check
    server server2 54.146.64.127:80 check
EOL

sudo service haproxy enable
sudo service haproxy restart

