#!/usr/bin/env bash
#displays best school 10 times
#on 4th iteration print bad luck
#on 8th iteration print good luck

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
